# Generated by Django 3.0.3 on 2021-11-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('key', models.CharField(max_length=1)),
                ('description', models.TextField(null=True)),
                ('flat_time', models.IntegerField()),
                ('position', models.SmallIntegerField()),
            ],
        ),
    ]
