# Generated by Django 3.2.9 on 2021-11-27 17:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211127_1110'),
        ('observation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=datetime.datetime.utcnow)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.source'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='ended',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observation',
            name='started',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='observation',
            name='observation_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='observation.observationlist'),
            preserve_default=False,
        ),
    ]
