# Generated by Django 3.2.9 on 2021-11-27 09:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('filter_wheel', '0002_alter_filter_id'),
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='exposure_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='exposure_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='filter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filter_wheel.filter'),
        ),
    ]
