# Generated by Django 3.2.9 on 2021-11-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20211127_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='exposure_start',
            new_name='exposure_started',
        ),
    ]
