# Generated by Django 3.2.9 on 2021-11-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_image_observer'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='fits_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
